Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> [ 70% 82464/116809] HIDL java: hardware/xiaomi/interfaces/hardware/motor/1.0/types.hal hardware/xiaomi/interfaces/hardware/motor/1.0/IMotor.hal hardware/xiaomi/interfaces/hardware/motor/1.0/IMotorCallback
> FAILED: out/soong/.intermediates/hardware/xiaomi/interfaces/hardware/motor/1.0/vendor.xiaomi.hardware.motor-V1.0-java_gen_java/gen/srcs.srcjar
> rm -rf out/soong/.intermediates/hardware/xiaomi/interfaces/hardware/motor/1.0/vendor.xiaomi.hardware.motor-V1.0-java_gen_java/gen && out/soong/host/linux-x86/bin/hidl-gen -R -p . -d out/soong/.intermediat
> es/hardware/xiaomi/interfaces/hardware/motor/1.0/vendor.xiaomi.hardware.motor-V1.0-java_gen_java/gen/srcs.srcjar.d -o out/soong/.intermediates/hardware/xiaomi/interfaces/hardware/motor/1.0/vendor.xiaomi.h
> ardware.motor-V1.0-java_gen_java/gen/srcs -L java -rvendor.xiaomi:device/xiaomi/common/interfaces -randroid.hidl:system/libhidl/transport vendor.xiaomi.hardware.motor@1.0 && out/soong/host/linux-x86/bin/s
> oong_zip -o out/soong/.intermediates/hardware/xiaomi/interfaces/hardware/motor/1.0/vendor.xiaomi.hardware.motor-V1.0-java_gen_java/gen/srcs.srcjar -C out/soong/.intermediates/hardware/xiaomi/interfaces/ha
> rdware/motor/1.0/vendor.xiaomi.hardware.motor-V1.0-java_gen_java/gen/srcs -D out/soong/.intermediates/hardware/xiaomi/interfaces/hardware/motor/1.0/vendor.xiaomi.hardware.motor-V1.0-java_gen_java/gen/srcs
> ERROR: Could not open package path device/xiaomi/common/interfaces/hardware/motor/1.0/ for package vendor.xiaomi.hardware.motor@1.0:
> ./device/xiaomi/common/interfaces/hardware/motor/1.0/
> ERROR: Could not get sources for vendor.xiaomi.hardware.motor@1.0.
> 12:52:01 ninja failed with: exit status 1

This is obvious. You're picking an open change that needs to be adapted. ;)

Patch-set: 3